// Mocks generated by Mockito 5.4.6 from annotations
// in bitnest/test/providers/send_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i12;
import 'dart:ui' as _i15;

import 'package:bitnest/models/account.dart' as _i5;
import 'package:bitnest/models/fee_estimate.dart' as _i2;
import 'package:bitnest/models/utxo.dart' as _i8;
import 'package:bitnest/models/wallet.dart' as _i4;
import 'package:bitnest/providers/wallet_provider.dart' as _i14;
import 'package:bitnest/services/broadcast_service.dart' as _i11;
import 'package:bitnest/services/key_service.dart' as _i9;
import 'package:bitnest/services/transaction_service.dart' as _i3;
import 'package:bitnest/utils/networks.dart' as _i10;
import 'package:local_auth/local_auth.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFeeEstimate_0 extends _i1.SmartFake implements _i2.FeeEstimate {
  _FakeFeeEstimate_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTxInputInfo_1 extends _i1.SmartFake implements _i3.TxInputInfo {
  _FakeTxInputInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWallet_2 extends _i1.SmartFake implements _i4.Wallet {
  _FakeWallet_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccount_3 extends _i1.SmartFake implements _i5.Account {
  _FakeAccount_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TransactionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionService extends _i1.Mock
    implements _i3.TransactionService {
  MockTransactionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> buildTransaction({
    required List<_i3.TxInputInfo>? inputs,
    required List<_i3.TxOutputInfo>? outputs,
    required int? feeRate,
    String? changeAddress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#buildTransaction, [], {
              #inputs: inputs,
              #outputs: outputs,
              #feeRate: feeRate,
              #changeAddress: changeAddress,
            }),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#buildTransaction, [], {
                  #inputs: inputs,
                  #outputs: outputs,
                  #feeRate: feeRate,
                  #changeAddress: changeAddress,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i2.FeeEstimate> getFeeEstimateForPreset(_i3.FeePreset? preset) =>
      (super.noSuchMethod(
            Invocation.method(#getFeeEstimateForPreset, [preset]),
            returnValue: _i6.Future<_i2.FeeEstimate>.value(
              _FakeFeeEstimate_0(
                this,
                Invocation.method(#getFeeEstimateForPreset, [preset]),
              ),
            ),
          )
          as _i6.Future<_i2.FeeEstimate>);

  @override
  _i6.Future<_i3.TxInputInfo> createInputInfo({
    required _i8.UTXO? utxo,
    required String? accountXprv,
    required int? addressIndex,
    required bool? isChange,
    required _i9.DerivationScheme? scheme,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createInputInfo, [], {
              #utxo: utxo,
              #accountXprv: accountXprv,
              #addressIndex: addressIndex,
              #isChange: isChange,
              #scheme: scheme,
            }),
            returnValue: _i6.Future<_i3.TxInputInfo>.value(
              _FakeTxInputInfo_1(
                this,
                Invocation.method(#createInputInfo, [], {
                  #utxo: utxo,
                  #accountXprv: accountXprv,
                  #addressIndex: addressIndex,
                  #isChange: isChange,
                  #scheme: scheme,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.TxInputInfo>);

  @override
  String deriveChangeAddress({
    required String? accountXpub,
    required int? currentChangeIndex,
    required _i9.DerivationScheme? scheme,
    required _i10.BitcoinNetwork? network,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deriveChangeAddress, [], {
              #accountXpub: accountXpub,
              #currentChangeIndex: currentChangeIndex,
              #scheme: scheme,
              #network: network,
            }),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#deriveChangeAddress, [], {
                #accountXpub: accountXpub,
                #currentChangeIndex: currentChangeIndex,
                #scheme: scheme,
                #network: network,
              }),
            ),
          )
          as String);
}

/// A class which mocks [BroadcastService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBroadcastService extends _i1.Mock implements _i11.BroadcastService {
  MockBroadcastService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> broadcastTransaction(String? txHex) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastTransaction, [txHex]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#broadcastTransaction, [txHex]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  void setNetwork(_i10.BitcoinNetwork? network) => super.noSuchMethod(
    Invocation.method(#setNetwork, [network]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [KeyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyService extends _i1.Mock implements _i9.KeyService {
  MockKeyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String generateMnemonic({int? wordCount = 24}) =>
      (super.noSuchMethod(
            Invocation.method(#generateMnemonic, [], {#wordCount: wordCount}),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#generateMnemonic, [], {#wordCount: wordCount}),
            ),
          )
          as String);

  @override
  bool validateMnemonic(String? mnemonic) =>
      (super.noSuchMethod(
            Invocation.method(#validateMnemonic, [mnemonic]),
            returnValue: false,
          )
          as bool);

  @override
  _i12.Uint8List mnemonicToSeed(String? mnemonic, {String? passphrase}) =>
      (super.noSuchMethod(
            Invocation.method(
              #mnemonicToSeed,
              [mnemonic],
              {#passphrase: passphrase},
            ),
            returnValue: _i12.Uint8List(0),
          )
          as _i12.Uint8List);

  @override
  String deriveMasterXprv(_i12.Uint8List? seed, _i10.BitcoinNetwork? network) =>
      (super.noSuchMethod(
            Invocation.method(#deriveMasterXprv, [seed, network]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#deriveMasterXprv, [seed, network]),
            ),
          )
          as String);

  @override
  String deriveMasterXpub(_i12.Uint8List? seed, _i10.BitcoinNetwork? network) =>
      (super.noSuchMethod(
            Invocation.method(#deriveMasterXpub, [seed, network]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#deriveMasterXpub, [seed, network]),
            ),
          )
          as String);

  @override
  String deriveXprv(String? xprv, String? derivationPath) =>
      (super.noSuchMethod(
            Invocation.method(#deriveXprv, [xprv, derivationPath]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#deriveXprv, [xprv, derivationPath]),
            ),
          )
          as String);

  @override
  String deriveXpub(String? xpub, String? derivationPath) =>
      (super.noSuchMethod(
            Invocation.method(#deriveXpub, [xpub, derivationPath]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#deriveXpub, [xpub, derivationPath]),
            ),
          )
          as String);

  @override
  String deriveAccountXpub(
    _i12.Uint8List? seed,
    _i9.DerivationScheme? scheme,
    _i10.BitcoinNetwork? network, {
    int? accountIndex = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deriveAccountXpub,
              [seed, scheme, network],
              {#accountIndex: accountIndex},
            ),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(
                #deriveAccountXpub,
                [seed, scheme, network],
                {#accountIndex: accountIndex},
              ),
            ),
          )
          as String);

  @override
  String derivePrivateKey(
    String? xprv,
    int? addressIndex, {
    bool? change = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #derivePrivateKey,
              [xprv, addressIndex],
              {#change: change},
            ),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(
                #derivePrivateKey,
                [xprv, addressIndex],
                {#change: change},
              ),
            ),
          )
          as String);

  @override
  String derivePublicKey(
    String? xpub,
    int? addressIndex, {
    bool? change = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #derivePublicKey,
              [xpub, addressIndex],
              {#change: change},
            ),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(
                #derivePublicKey,
                [xpub, addressIndex],
                {#change: change},
              ),
            ),
          )
          as String);

  @override
  String deriveAddress(
    String? xpub,
    int? addressIndex,
    _i9.DerivationScheme? scheme,
    _i10.BitcoinNetwork? network, {
    bool? change = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deriveAddress,
              [xpub, addressIndex, scheme, network],
              {#change: change},
            ),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(
                #deriveAddress,
                [xpub, addressIndex, scheme, network],
                {#change: change},
              ),
            ),
          )
          as String);

  @override
  _i6.Future<void> storeSeed(
    String? walletId,
    _i12.Uint8List? seed, {
    bool? requireBiometric = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #storeSeed,
              [walletId, seed],
              {#requireBiometric: requireBiometric},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i12.Uint8List?> retrieveSeed(
    String? walletId, {
    bool? requireBiometric = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #retrieveSeed,
              [walletId],
              {#requireBiometric: requireBiometric},
            ),
            returnValue: _i6.Future<_i12.Uint8List?>.value(),
          )
          as _i6.Future<_i12.Uint8List?>);

  @override
  _i6.Future<void> storeMnemonic(
    String? walletId,
    String? mnemonic, {
    bool? requireBiometric = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #storeMnemonic,
              [walletId, mnemonic],
              {#requireBiometric: requireBiometric},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> retrieveMnemonic(
    String? walletId, {
    bool? requireBiometric = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #retrieveMnemonic,
              [walletId],
              {#requireBiometric: requireBiometric},
            ),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> deleteWalletData(String? walletId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWalletData, [walletId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isBiometricAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isBiometricAvailable, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<_i13.BiometricType>> getAvailableBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableBiometrics, []),
            returnValue: _i6.Future<List<_i13.BiometricType>>.value(
              <_i13.BiometricType>[],
            ),
          )
          as _i6.Future<List<_i13.BiometricType>>);

  @override
  _i6.Future<bool> authenticateWithBiometrics({
    String? reason = 'Please authenticate',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authenticateWithBiometrics, [], {
              #reason: reason,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [WalletProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletProvider extends _i1.Mock implements _i14.WalletProvider {
  MockWalletProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.Wallet> get wallets =>
      (super.noSuchMethod(
            Invocation.getter(#wallets),
            returnValue: <_i4.Wallet>[],
          )
          as List<_i4.Wallet>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  List<_i5.Account> get currentAccounts =>
      (super.noSuchMethod(
            Invocation.getter(#currentAccounts),
            returnValue: <_i5.Account>[],
          )
          as List<_i5.Account>);

  @override
  BigInt get totalBalance =>
      (super.noSuchMethod(
            Invocation.getter(#totalBalance),
            returnValue: _i7.dummyValue<BigInt>(
              this,
              Invocation.getter(#totalBalance),
            ),
          )
          as BigInt);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  List<_i5.Account> getAccountsForWallet(String? walletId) =>
      (super.noSuchMethod(
            Invocation.method(#getAccountsForWallet, [walletId]),
            returnValue: <_i5.Account>[],
          )
          as List<_i5.Account>);

  @override
  List<_i8.UTXO> getAccountUtxos(String? accountId) =>
      (super.noSuchMethod(
            Invocation.method(#getAccountUtxos, [accountId]),
            returnValue: <_i8.UTXO>[],
          )
          as List<_i8.UTXO>);

  @override
  BigInt getAccountBalance(String? accountId) =>
      (super.noSuchMethod(
            Invocation.method(#getAccountBalance, [accountId]),
            returnValue: _i7.dummyValue<BigInt>(
              this,
              Invocation.method(#getAccountBalance, [accountId]),
            ),
          )
          as BigInt);

  @override
  bool isAccountSyncing(String? accountId) =>
      (super.noSuchMethod(
            Invocation.method(#isAccountSyncing, [accountId]),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<_i4.Wallet> createWallet({
    required String? label,
    required _i10.BitcoinNetwork? network,
    int? wordCount = 24,
    _i9.DerivationScheme? derivationScheme = _i9.DerivationScheme.nativeSegwit,
    String? mnemonic,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createWallet, [], {
              #label: label,
              #network: network,
              #wordCount: wordCount,
              #derivationScheme: derivationScheme,
              #mnemonic: mnemonic,
            }),
            returnValue: _i6.Future<_i4.Wallet>.value(
              _FakeWallet_2(
                this,
                Invocation.method(#createWallet, [], {
                  #label: label,
                  #network: network,
                  #wordCount: wordCount,
                  #derivationScheme: derivationScheme,
                  #mnemonic: mnemonic,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Wallet>);

  @override
  _i6.Future<_i4.Wallet> importWallet({
    required String? mnemonic,
    required String? label,
    required _i10.BitcoinNetwork? network,
    _i9.DerivationScheme? derivationScheme = _i9.DerivationScheme.nativeSegwit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#importWallet, [], {
              #mnemonic: mnemonic,
              #label: label,
              #network: network,
              #derivationScheme: derivationScheme,
            }),
            returnValue: _i6.Future<_i4.Wallet>.value(
              _FakeWallet_2(
                this,
                Invocation.method(#importWallet, [], {
                  #mnemonic: mnemonic,
                  #label: label,
                  #network: network,
                  #derivationScheme: derivationScheme,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Wallet>);

  @override
  _i6.Future<_i4.Wallet> importWatchOnlyWallet({
    required String? xpub,
    required String? label,
    required _i10.BitcoinNetwork? network,
    _i9.DerivationScheme? derivationScheme = _i9.DerivationScheme.nativeSegwit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#importWatchOnlyWallet, [], {
              #xpub: xpub,
              #label: label,
              #network: network,
              #derivationScheme: derivationScheme,
            }),
            returnValue: _i6.Future<_i4.Wallet>.value(
              _FakeWallet_2(
                this,
                Invocation.method(#importWatchOnlyWallet, [], {
                  #xpub: xpub,
                  #label: label,
                  #network: network,
                  #derivationScheme: derivationScheme,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Wallet>);

  @override
  _i6.Future<void> removeWallet(String? walletId) =>
      (super.noSuchMethod(
            Invocation.method(#removeWallet, [walletId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void selectWallet(String? walletId) => super.noSuchMethod(
    Invocation.method(#selectWallet, [walletId]),
    returnValueForMissingStub: null,
  );

  @override
  void deselectWallet() => super.noSuchMethod(
    Invocation.method(#deselectWallet, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i5.Account> createAccount({
    required String? label,
    _i9.DerivationScheme? derivationScheme = _i9.DerivationScheme.nativeSegwit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAccount, [], {
              #label: label,
              #derivationScheme: derivationScheme,
            }),
            returnValue: _i6.Future<_i5.Account>.value(
              _FakeAccount_3(
                this,
                Invocation.method(#createAccount, [], {
                  #label: label,
                  #derivationScheme: derivationScheme,
                }),
              ),
            ),
          )
          as _i6.Future<_i5.Account>);

  @override
  _i6.Future<String> deriveNextReceiveAddress(
    String? accountId, {
    _i9.DerivationScheme? derivationScheme,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deriveNextReceiveAddress,
              [accountId],
              {#derivationScheme: derivationScheme},
            ),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #deriveNextReceiveAddress,
                  [accountId],
                  {#derivationScheme: derivationScheme},
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  List<String> listAddresses(String? accountId) =>
      (super.noSuchMethod(
            Invocation.method(#listAddresses, [accountId]),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i6.Future<void> fetchAccountUtxos(String? accountId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAccountUtxos, [accountId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> syncAllAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#syncAllAccounts, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
