// Mocks generated by Mockito 5.4.6 from annotations
// in bitnest/test/providers/wallet_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i4;

import 'package:bitnest/services/key_service.dart' as _i2;
import 'package:bitnest/utils/networks.dart' as _i5;
import 'package:local_auth/local_auth.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [KeyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyService extends _i1.Mock implements _i2.KeyService {
  MockKeyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String generateMnemonic({int? wordCount = 24}) =>
      (super.noSuchMethod(
            Invocation.method(#generateMnemonic, [], {#wordCount: wordCount}),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#generateMnemonic, [], {#wordCount: wordCount}),
            ),
          )
          as String);

  @override
  bool validateMnemonic(String? mnemonic) =>
      (super.noSuchMethod(
            Invocation.method(#validateMnemonic, [mnemonic]),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Uint8List mnemonicToSeed(String? mnemonic, {String? passphrase}) =>
      (super.noSuchMethod(
            Invocation.method(
              #mnemonicToSeed,
              [mnemonic],
              {#passphrase: passphrase},
            ),
            returnValue: _i4.Uint8List(0),
          )
          as _i4.Uint8List);

  @override
  String deriveMasterXprv(_i4.Uint8List? seed, _i5.BitcoinNetwork? network) =>
      (super.noSuchMethod(
            Invocation.method(#deriveMasterXprv, [seed, network]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#deriveMasterXprv, [seed, network]),
            ),
          )
          as String);

  @override
  String deriveMasterXpub(_i4.Uint8List? seed, _i5.BitcoinNetwork? network) =>
      (super.noSuchMethod(
            Invocation.method(#deriveMasterXpub, [seed, network]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#deriveMasterXpub, [seed, network]),
            ),
          )
          as String);

  @override
  String deriveXprv(String? xprv, String? derivationPath) =>
      (super.noSuchMethod(
            Invocation.method(#deriveXprv, [xprv, derivationPath]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#deriveXprv, [xprv, derivationPath]),
            ),
          )
          as String);

  @override
  String deriveXpub(String? xpub, String? derivationPath) =>
      (super.noSuchMethod(
            Invocation.method(#deriveXpub, [xpub, derivationPath]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#deriveXpub, [xpub, derivationPath]),
            ),
          )
          as String);

  @override
  String deriveAccountXpub(
    _i4.Uint8List? seed,
    _i2.DerivationScheme? scheme,
    _i5.BitcoinNetwork? network, {
    int? accountIndex = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deriveAccountXpub,
              [seed, scheme, network],
              {#accountIndex: accountIndex},
            ),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(
                #deriveAccountXpub,
                [seed, scheme, network],
                {#accountIndex: accountIndex},
              ),
            ),
          )
          as String);

  @override
  String derivePrivateKey(
    String? xprv,
    int? addressIndex, {
    bool? change = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #derivePrivateKey,
              [xprv, addressIndex],
              {#change: change},
            ),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(
                #derivePrivateKey,
                [xprv, addressIndex],
                {#change: change},
              ),
            ),
          )
          as String);

  @override
  String derivePublicKey(
    String? xpub,
    int? addressIndex, {
    bool? change = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #derivePublicKey,
              [xpub, addressIndex],
              {#change: change},
            ),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(
                #derivePublicKey,
                [xpub, addressIndex],
                {#change: change},
              ),
            ),
          )
          as String);

  @override
  String deriveAddress(
    String? xpub,
    int? addressIndex,
    _i2.DerivationScheme? scheme,
    _i5.BitcoinNetwork? network, {
    bool? change = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deriveAddress,
              [xpub, addressIndex, scheme, network],
              {#change: change},
            ),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(
                #deriveAddress,
                [xpub, addressIndex, scheme, network],
                {#change: change},
              ),
            ),
          )
          as String);

  @override
  _i6.Future<void> storeSeed(
    String? walletId,
    _i4.Uint8List? seed, {
    bool? requireBiometric = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #storeSeed,
              [walletId, seed],
              {#requireBiometric: requireBiometric},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.Uint8List?> retrieveSeed(
    String? walletId, {
    bool? requireBiometric = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #retrieveSeed,
              [walletId],
              {#requireBiometric: requireBiometric},
            ),
            returnValue: _i6.Future<_i4.Uint8List?>.value(),
          )
          as _i6.Future<_i4.Uint8List?>);

  @override
  _i6.Future<void> storeMnemonic(
    String? walletId,
    String? mnemonic, {
    bool? requireBiometric = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #storeMnemonic,
              [walletId, mnemonic],
              {#requireBiometric: requireBiometric},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> retrieveMnemonic(
    String? walletId, {
    bool? requireBiometric = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #retrieveMnemonic,
              [walletId],
              {#requireBiometric: requireBiometric},
            ),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> deleteWalletData(String? walletId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWalletData, [walletId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isBiometricAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isBiometricAvailable, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<_i7.BiometricType>> getAvailableBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableBiometrics, []),
            returnValue: _i6.Future<List<_i7.BiometricType>>.value(
              <_i7.BiometricType>[],
            ),
          )
          as _i6.Future<List<_i7.BiometricType>>);
}
