// Mocks generated by Mockito 5.4.6 from annotations
// in bitnest/test/services/send_pipeline_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bitnest/services/broadcast_service.dart' as _i2;
import 'package:bitnest/utils/networks.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BroadcastService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBroadcastService extends _i1.Mock implements _i2.BroadcastService {
  MockBroadcastService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> broadcastTransaction(String? txHex) => (super.noSuchMethod(
        Invocation.method(
          #broadcastTransaction,
          [txHex],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #broadcastTransaction,
            [txHex],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  void setNetwork(_i5.BitcoinNetwork? network) => super.noSuchMethod(
        Invocation.method(
          #setNetwork,
          [network],
        ),
        returnValueForMissingStub: null,
      );
}
