// Mocks generated by Mockito 5.4.6 from annotations
// in bitnest/test/services/transaction_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i6;

import 'package:bitnest/models/fee_estimate.dart' as _i3;
import 'package:bitnest/models/transaction.dart' as _i2;
import 'package:bitnest/models/utxo.dart' as _i11;
import 'package:bitnest/services/api_service.dart' as _i10;
import 'package:bitnest/services/key_service.dart' as _i4;
import 'package:bitnest/utils/networks.dart' as _i7;
import 'package:local_auth/local_auth.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTransaction_0 extends _i1.SmartFake implements _i2.Transaction {
  _FakeTransaction_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFeeEstimate_1 extends _i1.SmartFake implements _i3.FeeEstimate {
  _FakeFeeEstimate_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [KeyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyService extends _i1.Mock implements _i4.KeyService {
  MockKeyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String generateMnemonic({int? wordCount = 24}) =>
      (super.noSuchMethod(
            Invocation.method(#generateMnemonic, [], {#wordCount: wordCount}),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#generateMnemonic, [], {#wordCount: wordCount}),
            ),
          )
          as String);

  @override
  bool validateMnemonic(String? mnemonic) =>
      (super.noSuchMethod(
            Invocation.method(#validateMnemonic, [mnemonic]),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Uint8List mnemonicToSeed(String? mnemonic, {String? passphrase}) =>
      (super.noSuchMethod(
            Invocation.method(
              #mnemonicToSeed,
              [mnemonic],
              {#passphrase: passphrase},
            ),
            returnValue: _i6.Uint8List(0),
          )
          as _i6.Uint8List);

  @override
  String deriveMasterXprv(_i6.Uint8List? seed, _i7.BitcoinNetwork? network) =>
      (super.noSuchMethod(
            Invocation.method(#deriveMasterXprv, [seed, network]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#deriveMasterXprv, [seed, network]),
            ),
          )
          as String);

  @override
  String deriveMasterXpub(_i6.Uint8List? seed, _i7.BitcoinNetwork? network) =>
      (super.noSuchMethod(
            Invocation.method(#deriveMasterXpub, [seed, network]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#deriveMasterXpub, [seed, network]),
            ),
          )
          as String);

  @override
  String deriveXprv(String? xprv, String? derivationPath) =>
      (super.noSuchMethod(
            Invocation.method(#deriveXprv, [xprv, derivationPath]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#deriveXprv, [xprv, derivationPath]),
            ),
          )
          as String);

  @override
  String deriveXpub(String? xpub, String? derivationPath) =>
      (super.noSuchMethod(
            Invocation.method(#deriveXpub, [xpub, derivationPath]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#deriveXpub, [xpub, derivationPath]),
            ),
          )
          as String);

  @override
  String deriveAccountXpub(
    _i6.Uint8List? seed,
    _i4.DerivationScheme? scheme,
    _i7.BitcoinNetwork? network, {
    int? accountIndex = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deriveAccountXpub,
              [seed, scheme, network],
              {#accountIndex: accountIndex},
            ),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(
                #deriveAccountXpub,
                [seed, scheme, network],
                {#accountIndex: accountIndex},
              ),
            ),
          )
          as String);

  @override
  String derivePrivateKey(
    String? xprv,
    int? addressIndex, {
    bool? change = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #derivePrivateKey,
              [xprv, addressIndex],
              {#change: change},
            ),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(
                #derivePrivateKey,
                [xprv, addressIndex],
                {#change: change},
              ),
            ),
          )
          as String);

  @override
  String derivePublicKey(
    String? xpub,
    int? addressIndex, {
    bool? change = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #derivePublicKey,
              [xpub, addressIndex],
              {#change: change},
            ),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(
                #derivePublicKey,
                [xpub, addressIndex],
                {#change: change},
              ),
            ),
          )
          as String);

  @override
  String deriveAddress(
    String? xpub,
    int? addressIndex,
    _i4.DerivationScheme? scheme,
    _i7.BitcoinNetwork? network, {
    bool? change = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deriveAddress,
              [xpub, addressIndex, scheme, network],
              {#change: change},
            ),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(
                #deriveAddress,
                [xpub, addressIndex, scheme, network],
                {#change: change},
              ),
            ),
          )
          as String);

  @override
  _i8.Future<void> storeSeed(
    String? walletId,
    _i6.Uint8List? seed, {
    bool? requireBiometric = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #storeSeed,
              [walletId, seed],
              {#requireBiometric: requireBiometric},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i6.Uint8List?> retrieveSeed(
    String? walletId, {
    bool? requireBiometric = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #retrieveSeed,
              [walletId],
              {#requireBiometric: requireBiometric},
            ),
            returnValue: _i8.Future<_i6.Uint8List?>.value(),
          )
          as _i8.Future<_i6.Uint8List?>);

  @override
  _i8.Future<void> storeMnemonic(
    String? walletId,
    String? mnemonic, {
    bool? requireBiometric = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #storeMnemonic,
              [walletId, mnemonic],
              {#requireBiometric: requireBiometric},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> retrieveMnemonic(
    String? walletId, {
    bool? requireBiometric = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #retrieveMnemonic,
              [walletId],
              {#requireBiometric: requireBiometric},
            ),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> deleteWalletData(String? walletId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWalletData, [walletId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isBiometricAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isBiometricAvailable, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<_i9.BiometricType>> getAvailableBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableBiometrics, []),
            returnValue: _i8.Future<List<_i9.BiometricType>>.value(
              <_i9.BiometricType>[],
            ),
          )
          as _i8.Future<List<_i9.BiometricType>>);

  @override
  _i8.Future<bool> authenticateWithBiometrics({
    String? reason = 'Please authenticate',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authenticateWithBiometrics, [], {
              #reason: reason,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i10.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.BitcoinNetwork get currentNetwork =>
      (super.noSuchMethod(
            Invocation.getter(#currentNetwork),
            returnValue: _i7.BitcoinNetwork.mainnet,
          )
          as _i7.BitcoinNetwork);

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  void setNetwork(_i7.BitcoinNetwork? network) => super.noSuchMethod(
    Invocation.method(#setNetwork, [network]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<BigInt> getAddressBalance(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#getAddressBalance, [address]),
            returnValue: _i8.Future<BigInt>.value(
              _i5.dummyValue<BigInt>(
                this,
                Invocation.method(#getAddressBalance, [address]),
              ),
            ),
          )
          as _i8.Future<BigInt>);

  @override
  _i8.Future<List<_i11.UTXO>> getAddressUtxos(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#getAddressUtxos, [address]),
            returnValue: _i8.Future<List<_i11.UTXO>>.value(<_i11.UTXO>[]),
          )
          as _i8.Future<List<_i11.UTXO>>);

  @override
  _i8.Future<List<_i2.Transaction>> getAddressTransactions(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#getAddressTransactions, [address]),
            returnValue: _i8.Future<List<_i2.Transaction>>.value(
              <_i2.Transaction>[],
            ),
          )
          as _i8.Future<List<_i2.Transaction>>);

  @override
  _i8.Future<_i2.Transaction> getTransaction(String? txid) =>
      (super.noSuchMethod(
            Invocation.method(#getTransaction, [txid]),
            returnValue: _i8.Future<_i2.Transaction>.value(
              _FakeTransaction_0(
                this,
                Invocation.method(#getTransaction, [txid]),
              ),
            ),
          )
          as _i8.Future<_i2.Transaction>);

  @override
  _i8.Future<String> getTransactionHex(String? txid) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionHex, [txid]),
            returnValue: _i8.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getTransactionHex, [txid]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<Map<int, int>> getFeeEstimates() =>
      (super.noSuchMethod(
            Invocation.method(#getFeeEstimates, []),
            returnValue: _i8.Future<Map<int, int>>.value(<int, int>{}),
          )
          as _i8.Future<Map<int, int>>);

  @override
  _i8.Future<_i3.FeeEstimate> getFeeEstimate({int? targetBlocks = 6}) =>
      (super.noSuchMethod(
            Invocation.method(#getFeeEstimate, [], {
              #targetBlocks: targetBlocks,
            }),
            returnValue: _i8.Future<_i3.FeeEstimate>.value(
              _FakeFeeEstimate_1(
                this,
                Invocation.method(#getFeeEstimate, [], {
                  #targetBlocks: targetBlocks,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.FeeEstimate>);

  @override
  _i8.Future<String> broadcastTransaction(String? txHex) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastTransaction, [txHex]),
            returnValue: _i8.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#broadcastTransaction, [txHex]),
              ),
            ),
          )
          as _i8.Future<String>);
}
