// Mocks generated by Mockito 5.4.6 from annotations
// in bitnest/test/services/utxo_scanner_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:bitnest/models/fee_estimate.dart' as _i3;
import 'package:bitnest/models/transaction.dart' as _i2;
import 'package:bitnest/models/utxo.dart' as _i8;
import 'package:bitnest/services/api_service.dart' as _i4;
import 'package:bitnest/utils/networks.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTransaction_0 extends _i1.SmartFake implements _i2.Transaction {
  _FakeTransaction_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFeeEstimate_1 extends _i1.SmartFake implements _i3.FeeEstimate {
  _FakeFeeEstimate_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.BitcoinNetwork get currentNetwork => (super.noSuchMethod(
        Invocation.getter(#currentNetwork),
        returnValue: _i5.BitcoinNetwork.mainnet,
      ) as _i5.BitcoinNetwork);

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  void setNetwork(_i5.BitcoinNetwork? network) => super.noSuchMethod(
        Invocation.method(
          #setNetwork,
          [network],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<BigInt> getAddressBalance(String? address) => (super.noSuchMethod(
        Invocation.method(
          #getAddressBalance,
          [address],
        ),
        returnValue: _i7.Future<BigInt>.value(_i6.dummyValue<BigInt>(
          this,
          Invocation.method(
            #getAddressBalance,
            [address],
          ),
        )),
      ) as _i7.Future<BigInt>);

  @override
  _i7.Future<List<_i8.UTXO>> getAddressUtxos(String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAddressUtxos,
          [address],
        ),
        returnValue: _i7.Future<List<_i8.UTXO>>.value(<_i8.UTXO>[]),
      ) as _i7.Future<List<_i8.UTXO>>);

  @override
  _i7.Future<List<_i2.Transaction>> getAddressTransactions(String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAddressTransactions,
          [address],
        ),
        returnValue:
            _i7.Future<List<_i2.Transaction>>.value(<_i2.Transaction>[]),
      ) as _i7.Future<List<_i2.Transaction>>);

  @override
  _i7.Future<_i2.Transaction> getTransaction(String? txid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransaction,
          [txid],
        ),
        returnValue: _i7.Future<_i2.Transaction>.value(_FakeTransaction_0(
          this,
          Invocation.method(
            #getTransaction,
            [txid],
          ),
        )),
      ) as _i7.Future<_i2.Transaction>);

  @override
  _i7.Future<String> getTransactionHex(String? txid) => (super.noSuchMethod(
        Invocation.method(
          #getTransactionHex,
          [txid],
        ),
        returnValue: _i7.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getTransactionHex,
            [txid],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<Map<int, int>> getFeeEstimates() => (super.noSuchMethod(
        Invocation.method(
          #getFeeEstimates,
          [],
        ),
        returnValue: _i7.Future<Map<int, int>>.value(<int, int>{}),
      ) as _i7.Future<Map<int, int>>);

  @override
  _i7.Future<_i3.FeeEstimate> getFeeEstimate({int? targetBlocks = 6}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeeEstimate,
          [],
          {#targetBlocks: targetBlocks},
        ),
        returnValue: _i7.Future<_i3.FeeEstimate>.value(_FakeFeeEstimate_1(
          this,
          Invocation.method(
            #getFeeEstimate,
            [],
            {#targetBlocks: targetBlocks},
          ),
        )),
      ) as _i7.Future<_i3.FeeEstimate>);

  @override
  _i7.Future<String> broadcastTransaction(String? txHex) => (super.noSuchMethod(
        Invocation.method(
          #broadcastTransaction,
          [txHex],
        ),
        returnValue: _i7.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #broadcastTransaction,
            [txHex],
          ),
        )),
      ) as _i7.Future<String>);
}
